front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
front_visiteur_index:
    path:     /visiteur
    defaults: { _controller: FrontBundle:Visiteur:index }
front_visiteur_liste_fiches:
        path:     /visiteur/fiches
        defaults: { _controller: FrontBundle:Visiteur:listeFiches }
front_comptable_index:
        path:     /comptable
        defaults: { _controller: FrontBundle:Comptable:index }
front_admin_index:
        path:     /admin
        defaults: { _controller: FrontBundle:Admin:index }