admin_compte_index:
    path:     /
    defaults: { _controller: "FrontBundle:Compte:index" }
    methods:  GET

admin_compte_show:
    path:     /{id}/show
    defaults: { _controller: "FrontBundle:Compte:show" }
    methods:  GET

admin_compte_new:
    path:     /new
    defaults: { _controller: "FrontBundle:Compte:new" }
    methods:  [GET, POST]

admin_compte_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontBundle:Compte:edit" }
    methods:  [GET, POST]

admin_compte_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontBundle:Compte:delete" }
    methods:  DELETE
